name: Deploy to Apps Script
on:
  push:
    branches:
      - main  # Jab bhi aap main branch par push karenge, ye chalega

jobs:
  deploy:
    runs-with: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Create clasprc.json
        run: echo "${{ secrets.CLASPRC_JSON }}" > ~/.clasprc.json

      - name: Push to Apps Script
        run: clasp push
